target: png.models.lit_denoising.LitDenoising

params: 
  misc_config: 
    compile: false                      # Set True to compile the model for faster training/inference.
    generator_pth: ~

  # Data configuration
  data_config: 
    train: 
      input_key: LQ                     # Key for input images in the batch.
      target_key: GT                    # Key for target images in the batch.
    validate: 
      SIDD: 
        input_key: LQ                   # Key for input images in the batch.
        target_key: GT                  # Key for target images in the batch.
      SIDDP: 
        input_key: LQ                   # Key for input images in the batch.
        target_key: GT                  # Key for target images in the batch.
      PolyU: 
        input_key: LQ                   # Key for input images in the batch.
        target_key: GT                  # Key for target images in the batch.
      Nam: 
        input_key: LQ                   # Key for input images in the batch.
        target_key: GT                  # Key for target images in the batch.

  # Optimizer configuration
  optimizer_config: 
    target: torch.optim.Adam
    params: 
      lr: !!float 1e-3                  # Learning rate.
      weight_decay: 0.                  # Weight decay (L2 penalty).
      betas: [0.9, 0.999]               # Coefficients used for computing running averages of gradient and its square.
      eps: !!float 1e-8                 # Term added to the denominator to improve numerical stability.

  # Loss configuration
  loss_config: 
    target: png.losses.basic_loss.L1Loss
    params: 
      loss_weight: !!float 1.0
      reduction: mean

  # Denoiser configuration
  denoiser_config: 
    target: png.archs.dncnn.DnCNN
    params: 
      in_nc: 3
      out_nc: 3
      nc: 64
      act_mode: 'BR'